### ISSUE TITLE
What is a valid DPD Tracking number ?

### ISSUE THREAD

**Issue by Leclowndu93150** [szkf/package-bot#17]
i can't seem to find the correct one

**Comment by szkf** [comment]
Hey @Leclowndu93150,

The DPD parcel number format usually consists of 14 digits.
Please provide me with the format of the number you are using. Perhaps it's a DPD reference number which is not supported yet.

**Comment by Leclowndu93150** [comment]
![image](https://github.com/szkf/package-bot/assets/73310949/55b5148d-1eca-4f83-8564-bb77577995ca)

**Comment by szkf** [comment]
This is a bug. I should be able to fix it today or tommorow.
Thank you for reporting it.

**Comment by Leclowndu93150** [comment]
I would have recieved my order by that time but Ty !

**Comment by szkf** [comment]
Hey @Leclowndu93150,

Unfortunately there isn't any official DPD tracking website that allows to track parcels in your country and doesn't block web scraping. Therefore I cannot fix this issue. You should be able to track GLS parcels, as GLS uses one tracking system for all their parcels.

**Comment by Leclowndu93150** [comment]
ty
